# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PROTO_FILE.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10PROTO_FILE.proto\x12\tPROTOFILE\"\x1e\n\x0cUnityRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1f\n\x0eServerResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x32\x61\n\x12UnityCommunication\x12K\n\x15UnityCommunicationRPC\x12\x17.PROTOFILE.UnityRequest\x1a\x19.PROTOFILE.ServerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PROTO_FILE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNITYREQUEST']._serialized_start=31
  _globals['_UNITYREQUEST']._serialized_end=61
  _globals['_SERVERRESPONSE']._serialized_start=63
  _globals['_SERVERRESPONSE']._serialized_end=94
  _globals['_UNITYCOMMUNICATION']._serialized_start=96
  _globals['_UNITYCOMMUNICATION']._serialized_end=193
# @@protoc_insertion_point(module_scope)
